basePath: /
definitions:
  controller.CreateOrderPayload:
    properties:
      client_id:
        format: uuid
        type: string
    required:
    - client_id
    type: object
  controller.HTTPError:
    properties:
      error:
        type: string
    type: object
  controller.UpdateOrderPayload:
    properties:
      status:
        example: paid
        type: string
    required:
    - status
    type: object
  order.Order:
    properties:
      client_id:
        type: string
      created_at:
        type: string
      id:
        type: string
      status:
        type: string
      total_amount:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: Fast Food API for FIAP Tech course
  title: Tech Challenge Order Food API
  version: 0.1.0
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: Get all order's list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/order.Order'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.HTTPError'
      summary: Get order list
      tags:
      - Order
    post:
      consumes:
      - application/json
      description: Create order from Cart
      parameters:
      - description: CreateOrderPayload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/controller.CreateOrderPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/order.Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/controller.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.HTTPError'
      summary: Create order from Cart
      tags:
      - Order
  /orders/{id}:
    get:
      consumes:
      - application/json
      description: Get an order by ID
      parameters:
      - description: ID of the order
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/order.Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/controller.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.HTTPError'
      summary: Get order by ID
      tags:
      - Order
    patch:
      consumes:
      - application/json
      description: Update by json an Order
      parameters:
      - description: ID of the Order
        in: path
        name: id
        required: true
        type: string
      - description: UpdateOrderPayload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/controller.UpdateOrderPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/order.Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/controller.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.HTTPError'
      summary: Update an Order
      tags:
      - Order
swagger: "2.0"
